version: "3.7"
services:
  pocketbase:
    build: 
      context: ./apps/pocketbase
      args: 
        - VERSION=0.19.4
    image: solid-pocketbase-dev
    container_name: solid-pocketbase-dev
    restart: unless-stopped
    # command: --debug
    ports:
      - "8090:8090"
    volumes:
      - ./apps/pocketbase/pb_data:/pb_data
      - ./apps/pocketbase:/srv/pocketbase
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
  server:
    build:
      context: ./apps/server
      dockerfile: Dockerfile.dev
      additional_contexts:
        monorepo: ./
    image: solid-server-dev
    volumes:
      - type: bind
        source: ./apps/server
        target: /home/solid/apps/server
    container_name: solid-server-dev
    restart: unless-stopped
    ports:
      - "3000:3000"