version: "3.7"
services:
  pocketbase:
    build: 
      context: .
      args: 
        - VERSION=0.22.8
    image: solid-pocketbase-local
    container_name: solid-pocketbase-local
    restart: unless-stopped
    # command: --debug
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/pb_data
      - .:/srv/pocketbase
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5